// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CTAButton: typeof import('./../src/components/common/CTAButton.vue')['default']
    DashboardHeader: typeof import('./../src/components/pages/dashboard/DashboardHeader.vue')['default']
    Default: typeof import('./../src/components/layouts/default.vue')['default']
    FormGroup: typeof import('./../src/components/pages/transactions/schedule-modal/utils/FormGroup.vue')['default']
    IconFaSolidAddressCard: typeof import('virtual:vite-icons/fa-solid/address-card')['default']
    IconIcBaselineAdd: typeof import('virtual:vite-icons/ic/baseline-add')['default']
    IconIcBaselineLogout: typeof import('virtual:vite-icons/ic/baseline-logout')['default']
    IconIcBaselineRemove: typeof import('virtual:vite-icons/ic/baseline-remove')['default']
    IconIcSharpDarkMode: typeof import('virtual:vite-icons/ic/sharp-dark-mode')['default']
    IconIcSharpLightMode: typeof import('virtual:vite-icons/ic/sharp-light-mode')['default']
    IconMdiKeyboardBackspace: typeof import('virtual:vite-icons/mdi/keyboard-backspace')['default']
    Modal: typeof import('./../src/components/common/Modal.vue')['default']
    RunTransaction: typeof import('./../src/components/pages/transactions/RunTransaction.vue')['default']
    RunTransactions: typeof import('./../src/components/pages/transactions/RunTransactions.vue')['default']
    ScheduleTransaction: typeof import('./../src/components/pages/transactions/schedule-modal/ScheduleTransaction.vue')['default']
    Spinner: typeof import('./../src/components/common/Spinner.vue')['default']
    TransactionActions: typeof import('./../src/components/pages/transactions/TransactionActions.vue')['default']
    TransactionAmount: typeof import('./../src/components/pages/transactions/schedule-modal/TransactionAmount.vue')['default']
    TransactionConfirm: typeof import('./../src/components/pages/transactions/schedule-modal/TransactionConfirm.vue')['default']
    TransactionDate: typeof import('./../src/components/pages/transactions/schedule-modal/TransactionDate.vue')['default']
    TransactionHeader: typeof import('./../src/components/pages/transactions/schedule-modal/utils/TransactionHeader.vue')['default']
    TransactionList: typeof import('./../src/components/pages/transactions/transaction-list/TransactionList.vue')['default']
    TransactionListEdgecase: typeof import('./../src/components/pages/transactions/transaction-list/TransactionListEdgecase.vue')['default']
    TransactionListItem: typeof import('./../src/components/pages/transactions/transaction-list/TransactionListItem.vue')['default']
    TransactionRecipient: typeof import('./../src/components/pages/transactions/schedule-modal/TransactionRecipient.vue')['default']
    Transactions: typeof import('./../src/components/pages/transactions/Transactions.vue')['default']
  }
}

export { }
