// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CTAButton: typeof import('./../src/components/common/CTAButton.vue')['default']
    DashboardHeader: typeof import('./../src/components/pages/dashboard/DashboardHeader.vue')['default']
    Default: typeof import('./../src/components/layouts/default.vue')['default']
    FormGroup: typeof import('./../src/components/pages/transactions/utils/FormGroup.vue')['default']
    IconFaSolidAddressCard: typeof import('virtual:vite-icons/fa-solid/address-card')['default']
    IconIcBaselineAdd: typeof import('virtual:vite-icons/ic/baseline-add')['default']
    IconIcBaselineLogout: typeof import('virtual:vite-icons/ic/baseline-logout')['default']
    IconIcBaselineRemove: typeof import('virtual:vite-icons/ic/baseline-remove')['default']
    IconIcSharpDarkMode: typeof import('virtual:vite-icons/ic/sharp-dark-mode')['default']
    IconIcSharpLightMode: typeof import('virtual:vite-icons/ic/sharp-light-mode')['default']
    IconMdiGear: typeof import('virtual:vite-icons/mdi/gear')['default']
    IconMdiKeyboardBackspace: typeof import('virtual:vite-icons/mdi/keyboard-backspace')['default']
    IconMdiSettings: typeof import('virtual:vite-icons/mdi/settings')['default']
    IconRiSettings3Line: typeof import('virtual:vite-icons/ri/settings3-line')['default']
    IconRiSettings4Line: typeof import('virtual:vite-icons/ri/settings4-line')['default']
    Modal: typeof import('./../src/components/common/Modal.vue')['default']
    Navbar: typeof import('./../src/components/common/Navbar.vue')['default']
    ScheduleTransaction: typeof import('./../src/components/pages/transactions/ScheduleTransaction.vue')['default']
    Spinner: typeof import('./../src/components/common/Spinner.vue')['default']
    TransactionAmount: typeof import('./../src/components/pages/transactions/TransactionAmount.vue')['default']
    TransactionConfirm: typeof import('./../src/components/pages/transactions/TransactionConfirm.vue')['default']
    TransactionDate: typeof import('./../src/components/pages/transactions/TransactionDate.vue')['default']
    TransactionHeader: typeof import('./../src/components/pages/transactions/utils/TransactionHeader.vue')['default']
    TransactionList: typeof import('./../src/components/pages/dashboard/TransactionList.vue')['default']
    TransactionListItem: typeof import('./../src/components/pages/dashboard/TransactionListItem.vue')['default']
    TransactionListState: typeof import('./../src/components/pages/dashboard/TransactionListState.vue')['default']
    TransactionRecipient: typeof import('./../src/components/pages/transactions/TransactionRecipient.vue')['default']
  }
}

export { }
